### ISSUE TITLE
How to re-implement the score-KL curve?

### ISSUE THREAD

**Issue by zetian1025** [tlc4418/llm_optimization#1]
Am I right:
1.  First sample D test prompts, then for each checkpoint (maybe saved with a fixed interval) generating one model output for each test prompt; 
2.  Performing sentence-level KL with a forward step using both policy model and reference model and then calculating scores for the D outputs (generated by the policy model); 
3.  Averaging the D results and get one point in the scatter diagram (as Figure 4,5)

**Comment by JohannesAck** [comment]
Hi @zetian1025 , did you find a good source for this question? I've been wondering about the same thing

**Comment by tlc4418** [comment]
Apologies for the delay in answering, will try to check the issues more often in the future. 

What @zetian1025 proposed sounds correct. The idea is to select *n* (e.g. 1000) test prompts, and perform a forward step for all of these, calculating the KL divergence between the current policy and the initial (reference) one, as well as the score for each prompt, and averaging over all *n* prompts.
