### ISSUE TITLE
5 Installation Errors

### ISSUE THREAD

**Issue by RylanSchaeffer** [tlc4418/llm_optimization#3]
When I try following the installation instructions, I've hit several errors. Putting them here:

1. `ModuleNotFoundError: No module named 'packaging` -> `pip install packaging`
2. `ModuleNotFoundError: No module named 'torch'` -> `pip install torch torchvision torchaudio`
3. Later, when I tried creating an SFT model using the pythia-70m config, I hit: `accelerate: command not found`
4. After installing `accelerate`, `ImportError: DeepSpeed is not installed => run `pip3 install deepspeed` or build it from source.`
5. `ModuleNotFoundError: No module named 'datasets'`

Is something wrong with the `pyproject.toml` file? Or did I do something incorrectly?

**Comment by RylanSchaeffer** [comment]
I might have run `pip install -e .` in the wrong directory :grimacing:

**Comment by tlc4418** [comment]
Haha no worries, I appreciate the idea of compiling errors you found!
