### ISSUE TITLE
When (not) to use Flash Attention?

### ISSUE THREAD

**Issue by RylanSchaeffer** [tlc4418/llm_optimization#8]
Some of the configs explicitly do not use flash attention. For instance, in `config_rl.yaml`, the `pythia_44m_rlhf_ensemble` sets `use_flash_attention` to false.

When is using flash attention (in)appropriate?

**Comment by tlc4418** [comment]
For this I kept the OpenAssitant defaults. I don't think it makes much of a difference, though you may be able to see some speedup by using flash attention more. I'd refer you to this PR where they merged flash-attention support: https://github.com/LAION-AI/Open-Assistant/pull/2033
